apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: admin
          resources:
            requests:
              cpu: 300m
              memory: 384Mi
            limits:
              cpu: "1"
              memory: 1Gi
          env:
            - name: NODE_ENV
              value: production
