apiVersion: batch/v1
kind: Job
metadata:
  name: db-v2-migrate
spec:
  template:
    spec:
      containers:
        - name: migrate
          env:
            - name: NODE_ENV
              value: production
