// Summarizes the synthesized ShopVoice CDK template into reviewable evidence:
// resource inventory plus the security-relevant settings. Run after
// `npm --prefix infra/aws run synth`. Writes docs/hackathon/evidence/cdk-synth-summary.md.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';

const dir = 'infra/aws/cdk.out';
const file = readdirSync(dir).find((f) => f.endsWith('.template.json'));
if (!file) throw new Error(`no template in ${dir}; run the synth first`);
const tpl = JSON.parse(readFileSync(`${dir}/${file}`, 'utf8'));
const resources = Object.entries(tpl.Resources ?? {});

const counts = new Map();
for (const [, r] of resources) counts.set(r.Type, (counts.get(r.Type) ?? 0) + 1);

const lines = [];
lines.push('# ShopVoice AWS stack: synthesized CloudFormation evidence', '');
lines.push(`Generated by \`scripts/demo/cdk_evidence.mjs\` from \`${dir}/${file}\` (\`cdk synth\`, aws-cdk-lib 2.270.0). Not deployed yet: see BLOCKERS.md B2.`, '');
lines.push(`**${resources.length} resources.**`, '', '| Resource type | Count |', '|---|---|');
for (const [type, n] of [...counts.entries()].sort()) lines.push(`| \`${type}\` | ${n} |`);

lines.push('', '## Security-relevant settings (read from the template)', '');
for (const [id, r] of resources) {
  const p = r.Properties ?? {};
  if (r.Type === 'AWS::EC2::LaunchTemplate') {
    const md = p.LaunchTemplateData?.MetadataOptions ?? {};
    lines.push(`- EC2 launch template \`${id}\`: IMDSv2 \`HttpTokens=${md.HttpTokens}\`, hop limit ${md.HttpPutResponseHopLimit}.`);
  }
  if (r.Type === 'AWS::EC2::Instance') {
    const md = p.MetadataOptions ?? {};
    const vols = (p.BlockDeviceMappings ?? []).map((b) => `${b.Ebs?.VolumeSize} GB ${b.Ebs?.VolumeType}, encrypted=${b.Ebs?.Encrypted}`);
    lines.push(`- EC2 instance \`${id}\`: type \`${p.InstanceType}\`, IMDSv2 \`HttpTokens=${md.HttpTokens}\` (hop limit ${md.HttpPutResponseHopLimit}), root volume ${vols.join('; ')}.`);
  }
  if (r.Type === 'AWS::EC2::SecurityGroup') {
    const ingress = (p.SecurityGroupIngress ?? []).map((i) => `${i.IpProtocol}/${i.FromPort}-${i.ToPort} from ${i.CidrIp ?? i.SourcePrefixListId ?? JSON.stringify(i.SourceSecurityGroupId ?? '?')}`);
    lines.push(`- Security group \`${id}\`: ingress ${ingress.length ? ingress.join('; ') : 'none'}. The ports are open so CloudFront can reach the origin; both apps reject any request without the secret \`X-Origin-Verify\` header that only the distributions add (see \`ORIGIN_VERIFY_SECRET\`, tested in \`tests/v2/mcp-http.test.mjs\`).`);
  }
  if (r.Type === 'AWS::IAM::Policy') {
    const actions = new Set();
    for (const st of p.PolicyDocument?.Statement ?? []) for (const a of [].concat(st.Action ?? [])) actions.add(a);
    lines.push(`- IAM policy \`${id}\`: ${[...actions].sort().map((a) => `\`${a}\``).join(', ')}.`);
  }
  if (r.Type === 'AWS::CloudFront::Distribution') {
    const c = p.DistributionConfig ?? {};
    const vp = c.DefaultCacheBehavior?.ViewerProtocolPolicy;
    const hdrs = (c.Origins ?? []).flatMap((o) => (o.OriginCustomHeaders ?? []).map((h) => h.HeaderName));
    lines.push(`- CloudFront \`${id}\`: viewer protocol \`${vp}\`, origin custom headers ${hdrs.length ? hdrs.map((h) => `\`${h}\``).join(', ') : 'none'}.`);
  }
  if (r.Type === 'AWS::Logs::LogGroup') {
    lines.push(`- Log group \`${id}\`: retention ${p.RetentionInDays ?? 'default'} days.`);
  }
}
lines.push('', '## Outputs', '');
for (const [k, v] of Object.entries(tpl.Outputs ?? {})) lines.push(`- \`${k}\`${v.Description ? `: ${v.Description}` : ''}`);
writeFileSync('docs/hackathon/evidence/cdk-synth-summary.md', `${lines.join('\n')}\n`);
console.log(`wrote docs/hackathon/evidence/cdk-synth-summary.md (${resources.length} resources)`);
