apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: migrate
automountServiceAccountToken: false
