apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: admin
  labels:
    app.kubernetes.io/component: admin
spec:
  type: ClusterIP
  selector:
    app: admin
  ports:
    - name: http
      port: 80
      targetPort: http

---
apiVersion: v1
kind: Service
metadata:
  name: worker-metrics
  labels:
    app.kubernetes.io/component: worker-metrics
spec:
  type: ClusterIP
  selector:
    app: worker
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
